name: Docker Build/Publish Image 
on:  
  push:    
    branches: [ master ]  
jobs:   
  build:    
    runs-on: ubuntu-18.04    
    env:      
      DOCKER_REGISTRY: kemansel.azurecr.io      
      DOCKER_IMAGE: kmansel/express-me      
      DOCKER_USERNAME: omka
      DOCKER_PASSWORD: 2096Hipopotam 
      DOCKER_TARGET_PLATFORM: linux/arm64                 
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v1          
    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest    
    - name: Prepare      
      if: success()      
      id: prepare      
      run: |        
        echo ::set-output name=docker_platform:: linux/arm64         
        echo ::set-output name=docker_image::omka/homeasistantview:latest    
        echo ::set-output name=version::test    
    - name: Docker Login      
      if: success()      
      run: |        
        echo "2096Hipopotam" | docker login omka --username "omka" --password-stdin          
    - name: Run Buildx (push image)      
      if: success()      
      run: |        
        docker buildx build \        --platform ${{ steps.prepare.outputs.docker_platform }} \        --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \        --file ./Dockerfile \        --output type=image,push=true .
